import { buildContinuousMetricDomain, type CaloriesTrendSummary, type HistoricalSummary, type MacroSplitSummary, type MacroTrendsSummary, type ProteinTrendSummary, type SpendTrendSummary } from '../../domain/analyticsCharts'
import type { DailyTotals, MacroGoals } from '../../storage'
import AnalyticsIcon from './AnalyticsIcon'
import CaloriesTrendChart from './CaloriesTrendChart'
import ProteinTrendChart from './ProteinTrendChart'
import SpendTrendChart from './SpendTrendChart'
import MacroSplitChart from './MacroSplitChart'
import MacroTrendsChart from './MacroTrendsChart'

const number = new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2 })
const caloriesNumber = new Intl.NumberFormat('en-IN', { maximumFractionDigits: 1 })
const money = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 })
const detailedMoney = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 0, maximumFractionDigits: 2 })
const metrics: Array<{ key: keyof DailyTotals; label: string; unit: string }> = [{ key: 'protein', label: 'Protein', unit: 'g' }, { key: 'calories', label: 'Calories', unit: 'kcal' }, { key: 'carbs', label: 'Carbs', unit: 'g' }, { key: 'fat', label: 'Fat', unit: 'g' }, { key: 'fibre', label: 'Fibre', unit: 'g' }, { key: 'cost', label: 'Cost', unit: '₹' }]
const value = (amount: number, unit: string) => unit === '₹' ? money.format(amount) : `${number.format(amount)} ${unit}`

export function AnalyticsSummaryGrid({ summary }: { summary: HistoricalSummary }) {
  const supporting = summary.trackedDays ? `Across ${summary.trackedDays} saved ${summary.trackedDays === 1 ? 'day' : 'days'}` : 'No saved data'
  const cards = [
    ['protein', 'Average Protein', summary.averageProtein === null ? '—' : `${number.format(summary.averageProtein)} g`, supporting],
    ['calories', 'Average Calories', summary.averageCalories === null ? '—' : `${number.format(summary.averageCalories)} kcal`, supporting],
    ['spend', 'Total Spend', summary.totalSpend === null ? '—' : money.format(summary.totalSpend), summary.trackedDays ? 'In this range' : 'No saved data'],
    ['tracked', 'Days Tracked', `${summary.trackedDays} of ${summary.rangeCapacity}`, summary.trackedDays ? 'In this range' : 'No saved data'],
  ] as const
  return <div className="analytics-summary-grid" aria-label="Historical summary">{cards.map(([icon, label, display, detail]) => <article className={`analytics-summary-card ${icon}`} key={label}><AnalyticsIcon name={icon} /><span>{label}</span><strong>{display}</strong><small>{detail}</small></article>)}</div>
}

export function AnalyticsChartShell({ trend, proteinGoal, caloriesTrend, caloriesGoal, spendTrend, costGoal, macroTrends, macroSplit, tickLabels, rangeStart, rangeEnd }: { trend: ProteinTrendSummary; proteinGoal: number | null; caloriesTrend: CaloriesTrendSummary; caloriesGoal: number | null; spendTrend: SpendTrendSummary; costGoal: number | null; macroTrends: MacroTrendsSummary; macroSplit: MacroSplitSummary; tickLabels: string[]; rangeStart: string; rangeEnd: string }) {
  const average = trend.averageProtein === null ? null : number.format(trend.averageProtein)
  const proteinDomain = buildContinuousMetricDomain({ values: trend.points.map((point) => point.proteinGrams), referenceValues: proteinGoal === null ? [] : [proteinGoal], minimumSpan: 30, paddingRatio: .1, roundingStep: 5, floorAtZero: true })
  const proteinSummaryText = trend.trackedDays ? `7-day range average: ${average}g across ${trend.trackedDays} saved ${trend.trackedDays === 1 ? 'day' : 'days'}.` : 'No saved protein data for this 7-day range.'

  const caloriesAverage = caloriesTrend.averageCalories === null ? null : caloriesNumber.format(caloriesTrend.averageCalories)
  const caloriesDomain = buildContinuousMetricDomain({ values: caloriesTrend.points.map((point) => point.caloriesKcal), referenceValues: caloriesGoal === null ? [] : [caloriesGoal], minimumSpan: 500, paddingRatio: .1, roundingStep: 100, floorAtZero: true })
  const caloriesSummaryText = caloriesTrend.trackedDays ? `7-day range average: ${caloriesAverage} kcal across ${caloriesTrend.trackedDays} saved ${caloriesTrend.trackedDays === 1 ? 'day' : 'days'}.` : 'No saved Calories data for this 7-day range.'

  const spendAverage = spendTrend.averageSpend === null ? null : detailedMoney.format(spendTrend.averageSpend)
  const spendDomain = buildContinuousMetricDomain({ values: spendTrend.points.map((point) => point.spendAmount), referenceValues: costGoal === null ? [] : [costGoal], minimumSpan: 100, paddingRatio: .1, roundingStep: 25, floorAtZero: true })
  const spendSummaryText = spendTrend.trackedDays ? `7-day range average: ${spendAverage} across ${spendTrend.trackedDays} saved ${spendTrend.trackedDays === 1 ? 'day' : 'days'}.` : 'No saved Spend data for this 7-day range.'
  const macroValues = macroTrends.days.flatMap((day) => [day.proteinGrams, day.carbsGrams, day.fatGrams, day.fibreGrams]).filter((value): value is number => value !== null)
  const macroDomain = buildContinuousMetricDomain({ values: macroValues, referenceValues: [], minimumSpan: 50, paddingRatio: .1, roundingStep: 10, floorAtZero: true })
  const macroStatusText = `Protein ${macroTrends.protein.trackedDays} observations; Carbs ${macroTrends.carbs.trackedDays}; Fat ${macroTrends.fat.trackedDays}; Fibre ${macroTrends.fibre.trackedDays}.`

  return <>
    <section className="analytics-section" aria-labelledby="protein-trend-title"><p className="eyebrow">HISTORICAL TRENDS</p><h2 id="protein-trend-title">Protein Trend</h2>{trend.status === 'empty' ? <div className="analytics-chart-shell"><AnalyticsIcon name="trend" /><strong>No saved data for this period.</strong><p>Save a day to History to begin your Protein Trend.</p><p>{proteinSummaryText}</p></div> : trend.status === 'insufficient' ? <div className="analytics-chart-shell protein-single"><strong>{number.format(trend.latestPoint!.proteinGrams)}g</strong><span>{trend.latestPoint!.dateLabel}</span><p>{proteinSummaryText}</p>{proteinGoal !== null && <p>Current goal · {number.format(proteinGoal)}g · {trend.latestPoint!.proteinGrams >= proteinGoal ? 'Goal met' : 'Below current goal'}</p>}<p>Save at least 2 days to view this trend.</p></div> : <div className="protein-trend-card"><p className="sr-only protein-interpretation" id="protein-trend-summary">{trend.trackedDays} saved days · Range {number.format(trend.minimumProtein!)}–{number.format(trend.maximumProtein!)}g · Latest {number.format(trend.latestPoint!.proteinGrams)}g on {trend.latestPoint!.dateLabel}. 7-day average: {average}g. {proteinGoal !== null ? `Current goal: ${number.format(proteinGoal)}g.` : 'Protein goal not set.'}</p><span className="sr-only" id="protein-trend-range-context">Selected context: complete seven-day local-calendar range.</span><ProteinTrendChart points={trend.points} domain={proteinDomain} tickLabels={tickLabels} average={trend.averageProtein} averageLabel={average} goal={proteinGoal} goalLabel={proteinGoal === null ? null : number.format(proteinGoal)} labelledBy="protein-trend-title" describedBy="protein-trend-summary protein-trend-range-context" /><table className="protein-trend-table"><caption className="sr-only">Protein Trend exact saved History values</caption><thead><tr><th>Date</th><th>Protein</th></tr></thead><tbody>{trend.points.map((point) => <tr key={point.id}><td>{point.dateLabel}</td><td>{number.format(point.proteinGrams)} grams</td></tr>)}</tbody></table></div>}</section>
    <section className="analytics-section" aria-labelledby="calories-trend-title"><p className="eyebrow">HISTORICAL TRENDS</p><h2 id="calories-trend-title">Calories Trend</h2>{caloriesTrend.status === 'empty' ? <div className="analytics-chart-shell calories-chart-shell"><AnalyticsIcon name="trend" /><strong>No saved Calories data for this period.</strong><p>Save a day to History to begin your Calories Trend.</p><p id="calories-trend-range-context">{caloriesSummaryText}</p></div> : caloriesTrend.status === 'insufficient' ? <div className="analytics-chart-shell protein-single calories-single"><strong>{caloriesNumber.format(caloriesTrend.latestPoint!.caloriesKcal)} kcal</strong><span>{caloriesTrend.latestPoint!.dateLabel}</span><p>{caloriesSummaryText}</p>{caloriesGoal !== null && <p>Current goal · {caloriesNumber.format(caloriesGoal)} kcal</p>}<p>Save at least 2 days to view this trend.</p></div> : <div className="protein-trend-card calories-trend-card"><p className="sr-only protein-interpretation" id="calories-trend-summary">{caloriesTrend.trackedDays} saved days · Range {caloriesNumber.format(caloriesTrend.minimumCalories!)}–{caloriesNumber.format(caloriesTrend.maximumCalories!)} kcal · Latest {caloriesNumber.format(caloriesTrend.latestPoint!.caloriesKcal)} kcal on {caloriesTrend.latestPoint!.dateLabel}. 7-day average: {caloriesAverage} kcal. {caloriesGoal !== null ? `Current goal: ${caloriesNumber.format(caloriesGoal)} kcal.` : 'Calories goal not set.'}</p><span className="sr-only" id="calories-trend-range-context">Selected context: complete seven-day local-calendar range from {rangeStart} to {rangeEnd}.</span><CaloriesTrendChart points={caloriesTrend.points} domain={caloriesDomain} tickLabels={tickLabels} average={caloriesTrend.averageCalories} averageLabel={caloriesAverage} goal={caloriesGoal} goalLabel={caloriesGoal === null ? null : caloriesNumber.format(caloriesGoal)} labelledBy="calories-trend-title" describedBy="calories-trend-summary calories-trend-range-context" /><table className="protein-trend-table calories-trend-table"><caption className="sr-only">Calories values for saved History days from {rangeStart} to {rangeEnd}.{caloriesGoal !== null ? ` Current Calories goal: ${caloriesNumber.format(caloriesGoal)} kcal.` : ''}</caption><thead><tr><th>Date</th><th>Calories</th></tr></thead><tbody>{caloriesTrend.points.map((point) => <tr key={point.id}><td>{point.dateLabel}</td><td>{caloriesNumber.format(point.caloriesKcal)} kcal</td></tr>)}</tbody></table></div>}</section>
    <section className="analytics-section" aria-labelledby="spend-trend-title"><p className="eyebrow">HISTORICAL TRENDS</p><h2 id="spend-trend-title">Spend Trend</h2>{spendTrend.status === 'empty' ? <div className="analytics-chart-shell spend-chart-shell"><AnalyticsIcon name="trend" /><strong>No saved Spend data for this period.</strong><p>Save a day to History to begin your Spend Trend.</p><p>{spendSummaryText}</p></div> : spendTrend.status === 'insufficient' ? <div className="analytics-chart-shell protein-single spend-single"><strong>{detailedMoney.format(spendTrend.latestPoint!.spendAmount)}</strong><span>{spendTrend.latestPoint!.dateLabel}</span><p>{spendSummaryText}</p>{costGoal !== null && <p>Current goal · {detailedMoney.format(costGoal)}</p>}<p>Save at least 2 days to view this trend.</p></div> : <div className="protein-trend-card spend-trend-card"><p className="sr-only protein-interpretation" id="spend-trend-summary">{spendTrend.trackedDays} saved days · Range {detailedMoney.format(spendTrend.minimumSpend!)}–{detailedMoney.format(spendTrend.maximumSpend!)} · Latest {detailedMoney.format(spendTrend.latestPoint!.spendAmount)} on {spendTrend.latestPoint!.dateLabel}. 7-day average: {spendAverage}. {costGoal !== null ? `Current goal: ${detailedMoney.format(costGoal)}.` : 'Cost goal not set.'}</p><span className="sr-only" id="spend-trend-range-context">Selected context: complete seven-day local-calendar range from {rangeStart} to {rangeEnd}.</span><SpendTrendChart points={spendTrend.points} domain={spendDomain} tickLabels={tickLabels} average={spendTrend.averageSpend} averageLabel={spendAverage} goal={costGoal} goalLabel={costGoal === null ? null : detailedMoney.format(costGoal)} labelledBy="spend-trend-title" describedBy="spend-trend-summary spend-trend-range-context" /><table className="protein-trend-table spend-trend-table"><caption className="sr-only">Spend values for saved History days from {rangeStart} to {rangeEnd}.{costGoal !== null ? ` Current Cost goal: ${detailedMoney.format(costGoal)}.` : ''}</caption><thead><tr><th>Date</th><th>Spend</th></tr></thead><tbody>{spendTrend.points.map((point) => <tr key={point.id}><td>{point.dateLabel}</td><td>{detailedMoney.format(point.spendAmount)}</td></tr>)}</tbody></table></div>}</section>
    <section className="analytics-section" aria-labelledby="macro-trends-title"><p className="eyebrow">HISTORICAL TRENDS</p><h2 id="macro-trends-title">Macro Trends</h2>{macroTrends.status === 'empty' ? <div className="analytics-chart-shell"><AnalyticsIcon name="trend" /><strong>No saved macro data for this 7-day range.</strong><p>Save a day to History to begin Macro Trends.</p></div> : macroTrends.status === 'insufficient' ? <div className="analytics-chart-shell"><AnalyticsIcon name="trend" /><strong>More macro history is needed.</strong><p>{macroStatusText}</p><p>Save at least 2 valid observations for one macro to view trends.</p></div> : <div className="protein-trend-card macro-trends-card"><p className="sr-only" id="macro-trends-summary">{macroStatusText}</p><span className="sr-only" id="macro-trends-range-context">Complete seven-day local-calendar range from {rangeStart} to {rangeEnd}.</span><MacroTrendsChart days={macroTrends.days} domain={macroDomain} tickLabels={tickLabels} labelledBy="macro-trends-title" describedBy="macro-trends-summary macro-trends-range-context" /><div className="macro-table-scroll"><table className="protein-trend-table macro-trends-table"><caption className="sr-only">Protein, Carbs, Fat, and Fibre values for saved History days from {rangeStart} to {rangeEnd}.</caption><thead><tr><th>Date</th><th>Protein</th><th>Carbs</th><th>Fat</th><th>Fibre</th></tr></thead><tbody>{macroTrends.days.map((day) => <tr key={day.id}><td>{day.dateLabel}</td>{[day.proteinGrams, day.carbsGrams, day.fatGrams, day.fibreGrams].map((value, index) => <td key={index}>{value === null ? '—' : `${number.format(value)}g`}</td>)}</tr>)}</tbody></table></div></div>}</section>
    <section className="analytics-section" aria-labelledby="macro-split-title"><p className="eyebrow">HISTORICAL TRENDS</p><h2 id="macro-split-title">Macro Split</h2><p className="macro-split-helper">7-day share by recorded grams</p>{macroSplit.status === 'empty' ? <div className="analytics-chart-shell"><strong>No complete macro data for this 7-day range.</strong></div> : macroSplit.status === 'zero' ? <div className="analytics-chart-shell"><strong>Recorded macro grams are zero.</strong><p>{macroSplit.completeDays} complete saved {macroSplit.completeDays === 1 ? 'day' : 'days'} are eligible, but there is no composition to display.</p></div> : <div className="protein-trend-card macro-split-card"><p className="sr-only" id="macro-split-summary">Share by recorded grams, not calorie contribution. {macroSplit.completeDays} complete saved days and {number.format(macroSplit.totalGrams)} aggregate grams. {macroSplit.data.map((item) => `${item.label}: ${number.format(item.grams)} grams, ${number.format(item.percentage!)} percent.`).join(' ')}</p><span className="sr-only" id="macro-split-range-context">Seven-day History range from {rangeStart} to {rangeEnd}.</span><MacroSplitChart data={macroSplit.data} labelledBy="macro-split-title" describedBy="macro-split-summary macro-split-range-context" /></div>}</section>
  </>
}

function Totals({ totals }: { totals: DailyTotals }) { return <><div className="analytics-primary-metrics">{metrics.slice(0, 2).concat(metrics.slice(5)).map(({ key, label, unit }) => <div key={key}><span>{label}</span><strong>{value(totals[key], unit)}</strong></div>)}</div><p className="analytics-secondary">Carbs {number.format(totals.carbs)} g · Fat {number.format(totals.fat)} g · Fibre {number.format(totals.fibre)} g</p></> }

export function AnalyticsTotalsSection({ kind, totals, plannedDays = 0 }: { kind: 'live' | 'planned'; totals: DailyTotals; plannedDays?: number }) { const live = kind === 'live'; return <section className="analytics-section analytics-data-card" aria-labelledby={`${kind}-analytics-title`}><div className="analytics-section-heading"><div><p className="eyebrow">{live ? 'LIVE TODAY' : 'PLANNED WEEK'}</p><h2 id={`${kind}-analytics-title`}>{live ? 'Today at a glance' : 'Planned Week'}</h2></div><span className={`analytics-badge ${live ? 'live' : 'planned'}`}><AnalyticsIcon name={live ? 'live' : 'planned'} />{live ? 'Live data' : 'Planned data'}</span></div><Totals totals={totals} /><footer>{live ? 'Current Today data is separate from saved History.' : `${plannedDays} of 7 days planned in Weekly Planner.`}</footer></section> }

export function AnalyticsGoals({ goals, totals }: { goals: MacroGoals; totals: DailyTotals }) { return <section className="analytics-section analytics-data-card" aria-labelledby="current-goals-title"><p className="eyebrow">CURRENT GOALS</p><h2 id="current-goals-title">Today compared with current goals</h2><div className="analytics-goal-list">{metrics.map(({ key, label, unit }) => { const goal = goals[key]; const valid = goal.enabled && goal.value !== null && Number.isFinite(goal.value) && goal.value > 0; if (!valid) return <div className="analytics-goal-row is-disabled" key={key}><span>{label}</span><strong>Goal not set</strong></div>; const percentage = Math.max(0, totals[key] / goal.value! * 100); return <div className="analytics-goal-row" key={key}><div><span>{label}</span><strong>{value(totals[key], unit)} of {value(goal.value!, unit)}</strong><b>{number.format(percentage)}%</b></div><div className="analytics-progress" role="progressbar" aria-label={`${label}: ${number.format(percentage)} percent of goal`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100, percentage)}><span style={{ width: `${Math.min(100, percentage)}%` }} /></div></div> })}</div><footer>Uses your current Settings goals and live Today totals.</footer></section> }
